# This workflow runs the test suite defined in tox.
#
# Note the python-version matrix, if new Python versions are wanted they need
# to be added in this matrix AS WELL as in the tox.ini file for
# "tox-gh-actions". Read more about tox-gh-actions on
# https://github.com/ymyzk/tox-gh-actions
name: Test package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [{%- for version in (range(cookiecutter.min_python | replace('3.', '') | int, 11)) -%}'3.{{ version }}'{{ ", " if not loop.last else ""}}{%- endfor %}]

    {% raw -%}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

      # To get completely reproducible builds these dependencies should be
      # pinned. For most smaller projects it should be ok to leave them
      # unpinend as they are stable projects.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Run tox
      run: tox
    {%- endraw %}
